sdm660-common: gps: Add namespace prefix for move()
Fix:
gps/utils/LocIpc.cpp:315:24: error: unqualified call to std::move [-Werror,-Wunqualified-std-cast-call]
            mIpcRecver(move(ipcRecver)) {}
                       ^
                       std::

Signed-off-by: Nanhumly <admin@warbler.cc>
Co-authored-by: Nanhumly <admin@warbler.cc>
Signed-off-by: Ghosuto <clash.raja10@gmail.com>
Signed-off-by: Rohit Tiwari <rohitttiwari52@gmail.com>